---
version: 2 
jobs: 
  build: 
    machine:
      enable: true
    steps: 
      - checkout 
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
  deploy: 
     machine:
      enable: true
     steps:
      - add_ssh_keys:
          fingerprints:
            - "89:18:ce:5f:4a:a7:de:37:77:7e:bb:51:dc:74:14:e4"
      - run: 
          name: do dir
          command: ls -la
      - run:
          name: install Software Properties
          command: sudo apt-get install software-properties-common 
      - run:
          name: connection AWS
          command: ssh ruchik@13.233.75.155
      - run:
          name: command check in AWS VM
          command: ls 
workflows:
  version: 2
  build_and_test: 
    jobs: 
     - build 
     - deploy